language: php
php:
  - 7.0
  - 7.1

cache:
  directories:
  - $HOME/.composer/cache

sudo: false

before_script:
  - travis_retry composer install --no-ansi --no-dev --no-interaction --no-progress --optimize-autoloader

script:
  - vendor/bin/phpcs --warning-severity=0 --standard=specstandards.xml ./.modman/
  - vendor/bin/phpcs --warning-severity=0 --standard=specstandards.xml ./src/

  - vendor/bin/phpmd ./.modman/ text phpmdstandards.xml --suffixes php,phtml
  - vendor/bin/phpmd ./src/ text phpmdstandards.xml --suffixes php
  - vendor/bin/phpmd ./app/design/frontend/{your template}/ text phpmdstandards.xml --suffixes php,phtml

  - vendor/bin/xmllint -e 'etc/' ./.modman/
  - vendor/bin/xmllint ./app/design/frontend/{your template}/layout

  - vendor/bin/phpunit --configuration phpunit.xml

notifications:
  email:
    recipients:
      - your@emailaddress.nl
    on_success: never
    on_failure: always

notifications:
  slack: {your slack channel name}:{token}
